language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get install -y libudev-dev libdbus-1-dev
addons:
  apt:
    update: true

cache: cargo
