[package]
name = "autokbswitcher"
version = "0.1.0"
authors = ["Greizgh <greizgh@ephax.org>"]

[dependencies]
libudev = "0.2.0"
notify-rust = "3.4.2"
serde = "1.0.70"
serde_derive = "1.0.70"
toml = "0.4.6"
xdg = "2.1.0"
