[package]
name = "usbautomator"
version = "0.3.0"
authors = ["Greizgh <greizgh@ephax.org>"]
readme = "README.md"
license = "GPL-3.0+"

[dependencies]
libudev = "0.2.0"
notify-rust = "3.4.2"
serde = "1.0.70"
serde_derive = "1.0.70"
structopt = "0.2.10"
toml = "0.4.6"
xdg = "2.1.0"
